# Verify source validation, target isolation and relocatable static exports.
file(REMOVE_RECURSE "${TEST_BINARY_DIR}")
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}/source")
file(WRITE "${TEST_BINARY_DIR}/source/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.20)
project(WamrIntegration C CXX)
set(CMAKE_C_STANDARD 11)
add_library(jfx_extif_common INTERFACE)
function(set_project_warnings target)
endfunction()
add_subdirectory("${ADAPTER_DIR}" adapter)
get_directory_property(definitions COMPILE_DEFINITIONS)
get_directory_property(includes INCLUDE_DIRECTORIES)
if(definitions MATCHES "WASM_|BH_PLATFORM" OR includes MATCHES "wasm-micro-runtime")
    message(FATAL_ERROR "WAMR directory settings leaked into its parent")
endif()
get_directory_property(runtime_definitions
    DIRECTORY "${ADAPTER_DIR}/runtime" COMPILE_DEFINITIONS)
foreach(setting WASM_ENABLE_INTERP=1 WASM_ENABLE_INSTRUCTION_METERING=1
        WASM_MEM_ALLOC_WITH_USAGE=1)
    if(NOT setting IN_LIST runtime_definitions)
        message(FATAL_ERROR "Missing WAMR setting: ${setting}")
    endif()
endforeach()
foreach(feature AOT JIT LIBC_WASI LIBC_BUILTIN THREAD_MGR)
    get_directory_property(value DIRECTORY "${ADAPTER_DIR}/runtime"
        DEFINITION WAMR_BUILD_${feature})
    if(NOT value STREQUAL "0")
        message(FATAL_ERROR "WAMR ${feature} must be disabled")
    endif()
endforeach()
install(TARGETS jfx_wasm jfx_wamr_runtime jfx_extif_common EXPORT Fixture)
install(EXPORT Fixture DESTINATION lib/cmake/Fixture)
]=])
function(configure_case name root expected diagnostic)
    execute_process(COMMAND "${CMAKE_COMMAND}"
        -S "${TEST_BINARY_DIR}/source" -B "${TEST_BINARY_DIR}/${name}"
        "-DADAPTER_DIR=${ADAPTER_DIR}" "-DJFX_WAMR_ROOT=${root}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(expected AND NOT result EQUAL 0)
        message(FATAL_ERROR "${name} failed: ${output}\n${errors}")
    elseif(NOT expected AND (result EQUAL 0 OR NOT "${output}\n${errors}" MATCHES "${diagnostic}"))
        message(FATAL_ERROR "${name} did not produce ${diagnostic}: ${output}\n${errors}")
    endif()
endfunction()
configure_case(missing "${TEST_BINARY_DIR}/missing" FALSE "JFX_EXT_WASM requires")
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}/old/build-scripts" "${TEST_BINARY_DIR}/old/core/iwasm/include")
file(WRITE "${TEST_BINARY_DIR}/old/build-scripts/runtime_lib.cmake" "")
file(WRITE "${TEST_BINARY_DIR}/old/core/iwasm/include/wasm_export.h" "")
configure_case(old "${TEST_BINARY_DIR}/old" FALSE "instruction metering support")
configure_case(vendored "${WAMR_ROOT}" TRUE "")
