# Exercise checkout selection and build isolation without compiling mruby.
if(NOT ADAPTER_DIR OR NOT TEST_BINARY_DIR)
    message(FATAL_ERROR "ADAPTER_DIR and TEST_BINARY_DIR are required")
endif()
file(REMOVE_RECURSE "${TEST_BINARY_DIR}")
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}/project")
file(COPY "${ADAPTER_DIR}/" DESTINATION "${TEST_BINARY_DIR}/adapter")
file(WRITE "${TEST_BINARY_DIR}/project/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 3.20)
project(MrubyConfiguration C)
function(set_project_warnings target)
endfunction()
add_library(jfx_extif_common INTERFACE)
add_library(tilly INTERFACE)
add_subdirectory("${ADAPTER_DIR}" adapter)
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/runtime.txt" CONTENT
    "$<TARGET_GENEX_EVAL:jfx_mruby_runtime,$<TARGET_PROPERTY:jfx_mruby_runtime,INTERFACE_LINK_LIBRARIES>>")
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/includes.txt" CONTENT
    "$<TARGET_PROPERTY:jfx_mruby,INCLUDE_DIRECTORIES>")
]=])
set(fake_rake [=[
require 'fileutils'
root = ENV.fetch('MRUBY_BUILD_DIR')
FileUtils.mkdir_p(root + '/jfx/lib')
FileUtils.mkdir_p(root + '/jfx/include/mruby/presym')
File.write(root + '/jfx/lib/libmruby.a', Dir.pwd)
File.write(root + '/jfx/include/mruby/presym/id.h', '/* generated */')
File.write(ENV.fetch('MRUBY_CONFIG') + '.lock', 'generated lock')
]=])
foreach(name IN ITEMS "sdk first" "sdk second" incompatible)
    file(MAKE_DIRECTORY "${TEST_BINARY_DIR}/${name}/include")
    file(WRITE "${TEST_BINARY_DIR}/${name}/minirake" "${fake_rake}")
    if(name STREQUAL "incompatible")
        file(WRITE "${TEST_BINARY_DIR}/${name}/include/mruby.h" "void mrb_open(void);\n")
    else()
        file(WRITE "${TEST_BINARY_DIR}/${name}/include/mruby.h" "void mrb_open_allocf(void);\n")
    endif()
endforeach()
file(SHA256 "${TEST_BINARY_DIR}/adapter/build_config.rb.lock" original_lock)
foreach(name IN ITEMS missing incompatible "sdk first" "sdk second")
    execute_process(COMMAND "${CMAKE_COMMAND}"
        -S "${TEST_BINARY_DIR}/project" -B "${TEST_BINARY_DIR}/build"
        "-DADAPTER_DIR=${TEST_BINARY_DIR}/adapter"
        "-DJFX_MRUBY_ROOT=${TEST_BINARY_DIR}/${name}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(name STREQUAL "missing" OR name STREQUAL "incompatible")
        if(result EQUAL 0 OR NOT "${output}\n${errors}" MATCHES "JFX_MRUBY_ROOT")
            message(FATAL_ERROR "Invalid mruby checkout needs setup guidance:\n${output}\n${errors}")
        endif()
        continue()
    endif()
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Compatible checkout configuration failed:\n${output}\n${errors}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${TEST_BINARY_DIR}/build"
        --target jfx_mruby_runtime_build
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Runtime build failed:\n${output}\n${errors}")
    endif()
    file(READ "${TEST_BINARY_DIR}/build/runtime.txt" archive)
    list(GET archive 0 archive)
    file(READ "${archive}" built_root)
    # Ruby's Dir.pwd may resolve a different alias of a symlinked workspace.
    file(REAL_PATH "${built_root}" built_root)
    file(REAL_PATH "${TEST_BINARY_DIR}/${name}" expected_root)
    if(NOT built_root STREQUAL expected_root OR archive STREQUAL previous_archive)
        message(FATAL_ERROR "Source checkout change reused the wrong runtime archive")
    endif()
    set(previous_archive "${archive}")
    get_filename_component(archive_dir "${archive}" DIRECTORY)
    get_filename_component(runtime "${archive_dir}/../.." ABSOLUTE)
    file(READ "${TEST_BINARY_DIR}/build/includes.txt" includes)
    list(FIND includes "${runtime}/jfx/include" generated_include)
    if(generated_include EQUAL -1 OR NOT EXISTS "${runtime}/build_config.rb.lock")
        message(FATAL_ERROR "Generated headers or lockfile are outside the selected build tree")
    endif()
    file(SHA256 "${TEST_BINARY_DIR}/adapter/build_config.rb.lock" current_lock)
    if(NOT current_lock STREQUAL original_lock)
        message(FATAL_ERROR "Runtime build modified the source lockfile")
    endif()
endforeach()
