include(GNUInstallDirs)

install(TARGETS jfx_core
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

install(DIRECTORY core/include/jfx
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
