add_executable(jfx_engine_benchmark engine_benchmark.c)
target_link_libraries(jfx_engine_benchmark PRIVATE jfx_core)
set_project_warnings(jfx_engine_benchmark)
add_executable(jfx_extif_benchmark "${PROJECT_SOURCE_DIR}/extif/tests/perf/benchmark.c")
target_link_libraries(jfx_extif_benchmark PRIVATE jfx_extif)
set_project_warnings(jfx_extif_benchmark)
add_custom_target(ext_perf COMMAND $<TARGET_FILE:jfx_extif_benchmark> DEPENDS jfx_extif_benchmark)
