add_subdirectory(common)

if(JFX_EXT_LUA)
    add_subdirectory(lua)
endif()
if(JFX_EXT_MRUBY)
    add_subdirectory(mruby)
endif()
if(JFX_EXT_QUICKJS)
    add_subdirectory(quickjs)
endif()
if(JFX_EXT_PYTHON)
    add_subdirectory(python)
endif()
if(JFX_EXT_WASM)
    add_subdirectory(wasm)
endif()
add_library(jfx_extif STATIC common/src/factory.c)
target_link_libraries(jfx_extif PUBLIC jfx_extif_common)
foreach(language IN ITEMS lua mruby quickjs python wasm)
    string(TOUPPER "${language}" option_name)
    target_compile_definitions(jfx_extif PRIVATE JFX_EXT_${option_name}=$<BOOL:${JFX_EXT_${option_name}}>)
    if(JFX_EXT_${option_name})
        target_link_libraries(jfx_extif PUBLIC jfx_${language})
    endif()
endforeach()
set_project_warnings(jfx_extif)
