#ifndef JFX_PROJECT_H
#define JFX_PROJECT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "jfx_compose.h"
#include "jfx_lut.h"
#include "jfx_timeline.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Project interchange.
 *
 * A sequence, a node graph and a grade are all described by one line-oriented
 * text format, so the desktop editor, the CLI, the web player, a phone app and a
 * host plugin all read and write the same documents. The format is deliberately
 * plain text: a project can be diffed, reviewed, generated by a script, and
 * read by a human debugging a render.
 *
 * Lines are whitespace-separated. `#` starts a comment. Unknown keys are an
 * error rather than being ignored, so a typo is reported instead of silently
 * changing the render.
 *
 * A graph document:
 *
 *     size 1920 1080
 *     node sweep                 Bars
 *     node exposure              Hot
 *     param 2 stops 1.0
 *     link 1 0 -> 2 0
 *     output 2
 *
 * Node numbers are 1-based. With no `output` line the last node declared is the
 * output. `param` and `string` name their node explicitly, so a document can be
 * edited without being read strictly in order. `graph` identifies an empty graph;
 * `output 0` means no output. `position NODE X Y` preserves graph-space layout.
 * Labels and string values may be quoted, with escaped whitespace, quotes and
 * backslashes. Legacy unquoted graph labels/strings consume the rest of the line.
 *
 * A sequence document:
 *
 *     size 1920 1080
 *     fps 30000 1001
 *     track V1
 *     clip solid 0 120 0.2 0.4 0.6 1.0 0 0 0 0   Opener
 *     effect exposure 1.0
 *     effect lut /looks/teal.cube 0.5
 *     track V2
 *     clip gradient 60 120 1 0 0  0 0 1  45   Wipe
 *     disable 1 1
 *     key 1 1 0 60 0.0
 *
 * A `clip` line is: source, then (for image/video/audio) its path, then the start frame
 * and length, then the eight source parameters, then an optional name. An
 * `effect` line is a kind, then its text fields, then its numeric parameters. A
 * `key`, `disable` or `opacity` line names a clip and an effect by their 1-based
 * order on the track.
 * Track/clip names and paths may be quoted with escaped quotes, backslashes and
 * whitespace. Sequence state directives track_state, clip_state, clip_keys and
 * effect_state retain source in-points, animation offsets and layer state;
 * track_audio and clip_audio preserve gain, balance, enable and fade clocks. See
 * docs/nle.md for their positional arguments and reference-clock key semantics.
 *
 * `param`, `string`, `position` and `link` name their node(s) explicitly. */

/* The largest document either reader accepts, so a malformed file cannot make a
 * caller allocate without bound. */
#define JFX_PROJECT_MAX_BYTES ((size_t)8u * 1024u * 1024u)
#define JFX_PROJECT_MAX_NODES JFX_GRAPH_MAX_NODES

/* ---- Graphs -------------------------------------------------------------- */

/* Parses a graph document. On success `*out_graph` owns a new graph and
 * `*out_output` is the explicit output, or the last node when omitted. Empty
 * documents/no output use UINT32_MAX. All output arguments are untouched on failure. */
jfx_result_t jfx_project_load_graph(const char *text, size_t length, jfx_graph_t **out_graph,
    uint32_t *out_output, uint32_t *out_width, uint32_t *out_height, char *out_error,
    size_t out_error_size);

/* Writes a graph. The raster is not part of a graph, so the caller supplies it
 * and the output begins with a `size` line. */
jfx_result_t jfx_project_save_graph(const jfx_graph_t *graph, uint32_t output, uint32_t width,
    uint32_t height, char *out_text, size_t out_size, size_t *out_written);

/* ---- Sequences ----------------------------------------------------------- */

/* Parses a sequence document into a new timeline. */
jfx_result_t jfx_project_load_sequence(const char *text, size_t length, jfx_timeline_t **out_timeline,
    char *out_error, size_t out_error_size);

/* Writes a sequence, including every track, clip, effect and key. */
jfx_result_t jfx_project_save_sequence(const jfx_timeline_t *timeline, char *out_text,
    size_t out_size, size_t *out_written);

/* Reads a file and dispatches on its first directive: `size` followed by
 * `track` is a sequence, a bare `size` followed by `node` is a graph. A caller
 * that knows which it wants should call the specific reader. */
typedef enum {
    JFX_PROJECT_KIND_SEQUENCE = 0,
    JFX_PROJECT_KIND_GRAPH,
    JFX_PROJECT_KIND_SCENE3D
} jfx_project_kind_t;

jfx_result_t jfx_project_kind_of(const char *text, size_t length, jfx_project_kind_t *out_kind,
    char *out_error, size_t out_error_size);

#ifdef __cplusplus
}
#endif

#endif /* JFX_PROJECT_H */
